### ISSUE TITLE
32. Integrate visualization tool for monitoring

### ISSUE THREAD

**Issue by sergey-morenets** [ohanke/game_shop#154]

**Comment by michaltworuszka** [comment]
@sergey-morenets  I have some issues with this. Look simple to add it to project. But added all like You on lecture and after starting all microservices. All modules are working but those which supposed to connect to Graphite giving me warning (below) and whatever I find in Web and try don't help. 
FYI - graphite is working - can go to localhost:80 and see it. Grafana also working and can connet to graphite
Please HELP!! 

Warning: 
WARN [users,,] 1 --- [rter-1-thread-1] c.c.metrics.graphite.GraphiteReporter    : Unable to report to Graphite

java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:583) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:507) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:319) ~[na:na]
        at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277) ~[na:na]
        at com.codahale.metrics.graphite.PickledGraphite.connect(PickledGraphite.java:185) ~[metrics-graphite-4.2.10.jar!/:4.2.10]
        at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:374) ~[metrics-graphite-4.2.10.jar!/:4.2.10]
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:253) ~[metrics-core-4.2.10.jar!/:4.2.10]
        at com.codahale.metrics.ScheduledReporter.lambda$start$0(ScheduledReporter.java:182) ~[metrics-core-4.2.10.jar!/:4.2.10]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]


POM files

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>game_shop</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>game_shop-users</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>game_shop-user-client</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>





        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.4.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>2.8.7</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-graphite</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>


docker-compose: 

version: '3.8'
services:
  
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - 80:80
      - 2003:2003
      - 2004:2004
      - 8125:8125
    networks:
      - spring
    volumes:
      - graphite:/graphite/storage
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  
  user:
    image: "users"
    container_name: users
    build:
      context: ./game_shop-users
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - eureka-server
      - broker
      - config-server
      - zipkin
      - graphite
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8090:8090"
    networks:
      - spring
      - postgres

  orders:
    image: "orders"
    container_name: orders
    build:
      context: ./game_shop-orders
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - eureka-server
      - broker
      - config-server
      - zipkin
      - graphite
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orders
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "9000:9000"
    networks:
      - spring
      - postgres
  
  notifications:
    image: "notifications"
    container_name: notifications
    build:
      context: ./game_shop-notifications
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - broker
      - config-server
      - zipkin
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8085:8085"
    networks:
      - spring
  
  eureka-server:
    image: "eureka-server"
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring
    depends_on:
      - zipkin
  
  config-server:
    image: "config-server"
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - zipkin
    ports:
      - "8888:8888"
    networks:
      - spring
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      - eureka-server
    networks:
      - spring
  
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - 29092:29092
    networks:
      - spring
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: on-failure
  
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
    ports:
      - "1001:8080"
      - "28081:28081"
  
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pageadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
    
volumes:
  postgres:
  pgadmin:
  graphite:

**Comment by sergey-morenets** [comment]
Hi

Did you run your microservices by Docker Compose ?

**Comment by michaltworuszka** [comment]
Yes. docker-compose build and then docker-compose up -d

**Comment by sergey-morenets** [comment]
So then you need to specify Graphite host in the microservice settings because by default it tries to connect to localhost.

**Comment by michaltworuszka** [comment]
Yes I'm sure of that but I couldn't find any information about how and where - how I can set that host (setting path in yml) and how to connect to it in docker Compose. I only found info that i need to do that but without any example

**Comment by sergey-morenets** [comment]
Please, review the documentation: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator
